config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:show, :index, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get 'search' => 'searches#search'
  get "tag_searches/search" => "tag_searches#search"

  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :messages, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'default-image'
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  # フォローされているか判定
  def followed?(user)
    followers.include?(user)
  end


  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @user = current_user
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def search
    user_books = User.find(params[:user_id]).books #user_idで取得したユーザの本の一覧を取得
    created_time = params[:created_at] #created_atをcreated_timeに代入
    if created_time == ""
      @search_book = "日付が選択されていません"
    else
      @search_book = user_books.where(created_at: created_time.to_date.all_day).count
    end
  end


  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.guest_user?
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
      <table class="table">
        <thead>
          <th><b>image</b></th>
          <th><b>name</b></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <% users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'default-image', size: "100x100" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数:<span class="followings-count_<%= user.id %>"><%= render "relationships/followings-count", user: user %></span>
              </td>
              <td>フォロワー数:<span class="followers-count_<%= user.id %>"><%= render "relationships/followers-count", user: user %></span>
              </td>
              <td>
                <% unless user == current_user %>
                  <div class="follow-btn_<%= user.id %>">
                    <%= render "relationships/follow", user: user %>
                  </div>
                <% end %>
              </td>
              <td><%=link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/_info.html.erb
    <% if user.profile_image.attached? %>
      <%= image_tag user.profile_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'default-image', size: "100x100" %>
    <% end %>
    <table class="table">
      <tbody>
        <tr>
          <td><b>name</b></td>
          <td><b><%= user.name %></b></td>
        </tr>
        <tr>
          <td><b>introduction</b></td>
          <td><b><%= user.introduction %></b></td>
        </tr>
        <tr>
          <td><b>follows</b></td>
          <td><b>
            <%= link_to user_followings_path(user) do %>
              <span class="followings-count_<%= user.id %>">
                <%= render "relationships/followings-count", user: user %>
              </span>
            <% end %>
          </b></td>
        </tr>
        <tr>
          <td><b>followers</b></td>
          <td><b>
            <%= link_to user_followers_path(user) do %>
              <span class="followers-count_<%= user.id %>">
                <%= render "relationships/followers-count", user: user %>
              </span>
            <% end %>
          </b></td>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <% unless user == current_user %>
        <div class="follow-btn_<%= user.id %>">
          <%= render "relationships/follow", user: user %>
        </div>
        <%= render "messages/chat-btn", user: user %>
      <% end %>
    </div>
    <% unless user.guest_user? %>
      <%=link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-cog" style="color: #8b8e92;"></i>
      <% end %>
    <% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="col-6 mx-auto">
    <h1>User info</h1>
    <%= render "layouts/error", obj: @user %>
    <%= form_with model: @user do |f| %>
      <h4>Name</h4>
      <%= f.text_field :name %>
      <h4>Image</h4>
      <%= f.file_field :profile_image, accept: "image/*" %>
      <h4>Introduction</h4>
      <%= f.text_area :introduction %><br>
      <%= f.submit "Update User", :class => "btn btn-sm btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="col-md-3">
      <h1>Users info</h1>
      <%= render 'info', user: current_user %>
      <h1>New book</h1>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="col-md-3">
      <h1>Users info</h1>
      <%= render 'info', user: @user %>
      <h1>New book</h1>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <%= render 'books/index',books: @books %>

      <div class ="mb-4">
        <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit '検索', class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div id="search_result"> <%#非同期化のためidを指定%>
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>

      <h3>投稿数の前日比・前週比</h3>
        <div class="table_width">
          <table class="table table-bordered">
            <thead>
            <tr>
              <th>今日の投稿</th>
              <th>昨日の投稿</th>
              <th>前日比</th>
            </tr>
            </thead>
            <tbody>
              <tr>
      	  <td><%= @today_book.count %></td>
      	  <td><%= @yesterday_book.count %></td>
              <% if @yesterday_book.count == 0 %>
      	  <td>前日の投稿はなし</td>
              <% else %>
      	  <td><% @the_day_before =   @today_book.count / @yesterday_book.count  %>
      	  <%= (@the_day_before * 100).round %>%</td>
              <% end %>
              </tr>
            </tbody>
          </table>

          <table class="table table-bordered">
            <thead>
            <tr>
              <th>今週の投稿</th>
              <th>先週の投稿</th>
              <th>先週比</th>
            </tr>
            </thead>
            <tbody>
              <tr>
      	  <td><%= @this_week_book.count %></td>
      	  <td><%= @last_week_book.count %></td>
              <% if @last_week_book.count == 0 %>
      	  <td>先週の投稿はなし</td>
              <% else %>
      	  <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
      	  <%= (@the_week_before * 100).round %>%</td>
              <% end %>
              </tr>
            </tbody>
          </table>

      <h4>7日間分の投稿数</h4>
        <table class='table table-bordered'>
          <thead>
            <tr>
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>１日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_days_ago(6).count %></td>
              <td><%= @books.created_days_ago(5).count %></td>
              <td><%= @books.created_days_ago(4).count %></td>
              <td><%= @books.created_days_ago(3).count %></td>
              <td><%= @books.created_days_ago(2).count %></td>
              <td><%= @books.created_yesterday.count %></td>
              <td><%= @books.created_today.count %></td>
            </tr>
          </tbody>
        </table>

      <canvas id="myLineChart"></canvas>
        <script>
          $(document).on('turbolinks:load', function() {
            var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                datasets: [
                  {
                    label: '投稿した本の数',
                    data: [
                      <%= @books.created_days_ago(6).count %>,
                      <%= @books.created_days_ago(5).count %>,
                      <%= @books.created_days_ago(4).count %>,
                      <%= @books.created_days_ago(3).count %>,
                      <%= @books.created_days_ago(2).count %>,
                      <%= @books.created_yesterday.count %>,
                      <%= @books.created_today.count %>
                    ],
                    borderColor: "rgba(0,0,255,1)",
                    backgroundColor: "rgba(0,0,0,0)",
                    tension: 0.4
                  }
                ],
              },
              options: {
                plugins: {
                  title: {
                    display: true,
                    text: '7日間の投稿数の比較',
                    position: 'top',
                    align: 'center'
                  }
                },
                responsive: true,
                scales: {
                  y:{
                    suggestedMin: 0,
                    suggestedMax: 10
                    beginAtZero: true
                  },
                  x:{
                    stacked: true
                  },
                },
              }
            });
          });
        </script>

    </div>
  </div>
</div>