config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:show, :index, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get 'search' => 'searches#search'
  get "tag_searches/search" => "tag_searches#search"

  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
    scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
    scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }
    scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
    scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(search,word)
    if search == "forward_match"
      @book = Book.where("title LIKE? OR body LIKE?","#{word}%","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE? OR body LIKE?","%#{word}","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("title LIKE? OR body LIKE?","#{word}","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE? OR body LIKE?","%#{word}%","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def index
    @books = Book.all.order(params[:sort])
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
    def book_params
      params.require(:book).permit(:title, :body, :score, :category)
    end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
      <%= form_with model: book do |f| %>
        <h5>Title</h5>
        <%= f.text_field :title, class: "form-control" %>
        <h5>Opinion</h5>
        <%= f.text_area :body, class: "form-control" %>
        <h5>Rate</h5>
        <% if book.id.nil? %>
          <div id="post_raty"></div>
        <% else %>
          <%= render "star", book: book %>
        <% end %>
        <h5>Category</h5>
        <%= f.text_field :category, class: "form-control book_category" %>
        <br>
        <%= f.submit :class => "btn btn-sm btn-success" %>

      <script>
        // scriptファイルをどのidの部分に配置するかを指定
        $(document).on('turbolinks:load', function() {
          let elem = document.querySelector('#post_raty');
          if(elem == null) return;

          elem.innerHTML = ""
          let opt = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            half: true,
            scoreName: 'book[score]',
            };
          raty(elem,opt);
        });
      </script>

      <% end %>

app/views/books/_index.html.erb
      <table class="table">
        <thead>
          <th></th>
          <th><b>Title</b></th>
          <th><b>Opinion</b></th>
          <th><b>Tag</b></th>
          <th colspan="4"></th>
        </thead>
        <tbody>
          <% books.each do |book| %>
          <tr>
            <td>
              <% if book.user.profile_image.attached? %>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.profile_image, size: "100x100" %>
                <% end %>
              <% else %>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag 'default-image', size: "100x100" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%=link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <td>
              <% if book.category.present? %>
                <%= link_to book.category, tag_searches_search_path(content: book.category) %>
              <% end %>
            </td>
            <td class="favorite-btn_<%= book.id %>">
              <%= render 'favorites/favorite-btn', book: book %>
            </td>
            <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
            <td>
              <%= render 'books/star', book: book %>
            </td>
            <td>閲覧数: <%= book.view_counts.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/books/_star.html.erb
<div id="star_<%= book.id %>"></div>
<script>
        $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#star_<%= book.id %>');
        if(elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          score: "<%= book.score %>",
          half: true,
          readOnly: true,
        };
        raty(elem, opt);
      });
</script>

app/views/books/edit.html.erb
<div class="container">
  <div class="col-6 mx-auto">
    <h1>Editing Book</h1>
    <%= render 'layouts/error', obj: @book %>
    <%= render 'form', book: @book %>
      <%=link_to "Show", book_path(@book.id) %>
      |
      <%=link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render 'layouts/error', obj: @book %>
  <div class="row mx-auto">
    <div class="col-md-3">
      <h1>Users info</h1>
      <%= render 'users/info', user: current_user %>
      <h1>New book</h1>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %>
      |
      <%= link_to "評価の高い順", books_path(sort: 'score DESC') %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <%= render 'layouts/error', obj: Book.new %>
  <div id ="comments-error"></div>
  <div class="row mx-auto">
    <div class="col-md-3">
      <h1>Users info</h1>
      <%= render 'users/info', user: current_user %>
      <h1>New book</h1>
      <%= render 'form', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
          <tr id="book_<%= @book.id %>">
            <td>
              <a href="/users/#{@book.user_id}">
                <% if @book.user.profile_image.attached? %>
                  <%= image_tag @book.user.profile_image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'default-image', size: "100x100" %>
                <% end %>
                <br>
                <%=link_to @book.user.name, user_path(@book.user_id) %>
              </a>
            </td>
            <td>
              <%=link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.category.present? %>
                <%= link_to @book.category, tag_searches_search_path(content: @book.category) %>
              <% end %>
            </td>
            <td class="favorite-btn_<%= @book.id %>">
              <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>
            <td>
              <%= render 'star', book: @book %>
            </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%=link_to "Edit", edit_book_path(@book.id), :class => "btn btn-sm btn-success"%>
              <% end %>
            </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%=link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?", :class => "btn btn-sm btn-danger" %>
              <% end %>
            </td>
            <td>閲覧数: <%= @book.view_counts.count %></td>
          </tr>
        </tbody>
      </table>
        <div class="comments">
          <%= render 'book_comments/comment', book: @book %>
        </div>
        <div class="comment-form">
          <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
        </div>
    </div>
  </div>
</div>