config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
  end

  resources :books, only: [:show, :index, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get 'search' => 'searches#search'
  get "tag_searches/search" => "tag_searches#search"

  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
    scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
    scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }
    scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
    scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(search,word)
    if search == "forward_match"
      @book = Book.where("title LIKE? OR body LIKE?","#{word}%","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE? OR body LIKE?","%#{word}","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("title LIKE? OR body LIKE?","#{word}","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE? OR body LIKE?","%#{word}%","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true, length: { maximum: 400 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'default-image.jpg'
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end


end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :send_user, class_name: 'User'
  belongs_to :receive_user, class_name: 'User'
  validates :chat, presence: true, length: { maximum: 140 }

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :messages, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'default-image'
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  # フォローされているか判定
  def followed?(user)
    followers.include?(user)
  end


  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tag_searches_helper.rb
module TagSearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
  <div class="col-md-8">
    <% if obj.errors.any? %>
      <h2><%= obj.errors.count %>error prohibited this obj from being saved:</h2>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

app/views/layouts/_footer.html.erb
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
    <header>
      <nav class="navbar navbar-expand-lg navbar-light navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3 text-white" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto text-decoration-none">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), :class => "text-white mx-3" do %>
                    <i class="fa-solid fa-home" style="color: #ffffff;"></i>
                    <span>Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-users" style="color: #ffffff;"></i>
                    <span>Users</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-book-open" style="color: #ffffff;"></i>
                    <span>Books</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-sign-out-alt" style="color: #ffffff;"></i>
                    <span>Log out</span>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-home" style="color: #ffffff;"></i>
                    <span>Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-link" style="color: #ffffff;"></i>
                    <span>About</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-user-plus" style="color: #ffffff;"></i>
                    <span>Sign up</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, :class => "text-white m-3" do %>
                    <i class="fa-solid fa-sign-in-alt" style="color: #ffffff;"></i>
                    <span>Log in</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0fb1231c25.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="d-flex justify-content-center">
      <%= render 'searches/form' %>
      <%= render 'tag_searches/tagsearch' %>
    </div>
    <main>
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>